# fly.toml app configuration file generated for wswp on 2023-08-07T09:45:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wswp"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]