"""added submission table and submitted_by to activities

Revision ID: 40b872b8b413
Revises: eddaa6733e5f
Create Date: 2020-12-13 18:52:52.082719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b872b8b413'
down_revision = 'eddaa6733e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('price_desc', sa.String(length=100), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.String(length=256), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity', sa.Column('submitted_by', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'submitted_by')
    op.drop_table('submissions')
    # ### end Alembic commands ###
