"""added creation date for activities

Revision ID: eddaa6733e5f
Revises: 2252876be057
Create Date: 2020-12-13 13:07:21.464857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddaa6733e5f'
down_revision = '2252876be057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'created_date')
    # ### end Alembic commands ###
