"""removed category table and linkage for now, removed price_desc as it is redundant

Revision ID: ef0aeb3dc591
Revises: 40b872b8b413
Create Date: 2020-12-20 16:24:52.569477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0aeb3dc591'
down_revision = '40b872b8b413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_category_id_fkey', 'activity', type_='foreignkey')
    op.drop_column('activity', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('activity_category_id_fkey', 'activity', 'category', ['category_id'], ['id'])
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    # ### end Alembic commands ###
