name: run-pytest
on: push

jobs:
  run-tests:
    name: Run all API unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.17
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.17
      - name: Start up database Docker container
        run: |
          docker-compose up -d db
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Create testing database
        run: |
          flask admin create-test-db
      - name: Run Pytest
        run: |
          pytest -v