name: run-pytest
on: push

jobs:
  run-tests:
    name: Run all API unit tests
    runs-on: ubuntu-latest
    container: python:3.9.17-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: wswp
          POSTGRES_PASSWORD: supersecure
          POSTGRES_DB: wswp_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Pytest
        run: |
          pytest -v